jobs:
  coverage:
    if: github.ref_type == 'branch'
    name: Check code coverages
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16
          - 18
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup modules
        run: npm ci
      - name: Check code coverages
        run: npm test
      - if: ${{ always() }}
        name: Archive code coverages report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report-${{ github.event.repository.name }}-${{ matrix.node }}
          path: coverage
name: Coverage
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.github/dependabot.yml'
      - '.gitignore'
      - 'LICENSE'
